apiVersion: v1
kind: Service
metadata:
  name: distributor
  namespace: loki
spec:
  ports:
  - name: distributor-http-metrics
    port: 80
    targetPort: 80
  - name: distributor-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: distributor
