apiVersion: v1
kind: Service
metadata:
  name: table-manager
  namespace: loki
spec:
  ports:
  - name: table-manager-http-metrics
    port: 80
    targetPort: 80
  - name: table-manager-grpc
    port: 9095
    targetPort: 9095
  selector:
    name: table-manager
